// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourManagement.Data.Context;

#nullable disable

namespace TourManagement.Data.Migrations
{
    [DbContext(typeof(TourManagementDbContext))]
    [Migration("20260702021946_RemoveUnusedBookingColumns")]
    partial class RemoveUnusedBookingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TourManagement.Data.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("AdultCount")
                        .HasColumnType("int");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChildCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("InfantCount")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PromoCodeId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequest")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 101,
                            AdultCount = 2,
                            BookingCode = "BK-20230601-101",
                            BookingDate = new DateTime(2026, 6, 27, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9672),
                            ChildCount = 0,
                            CreatedDate = new DateTime(2026, 7, 2, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9664),
                            CustomerName = "Nguyễn Văn A",
                            DiscountAmount = 0m,
                            Email = "nguyenvan@gmail.com",
                            FinalPrice = 5000000m,
                            InfantCount = 0,
                            PhoneNumber = "0901234567",
                            ScheduleId = 1,
                            SpecialRequest = "Phòng view biển nếu có thể",
                            Status = "Paid",
                            TotalPrice = 5000000m
                        },
                        new
                        {
                            BookingId = 102,
                            AdultCount = 2,
                            BookingCode = "BK-20230602-102",
                            BookingDate = new DateTime(2026, 6, 30, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9680),
                            ChildCount = 1,
                            CreatedDate = new DateTime(2026, 7, 2, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9676),
                            CustomerName = "Lê Thị B",
                            DiscountAmount = 0m,
                            Email = "lethi@gmail.com",
                            FinalPrice = 8640000m,
                            InfantCount = 0,
                            PhoneNumber = "0987654321",
                            ScheduleId = 2,
                            SpecialRequest = "Có trẻ em đi kèm",
                            Status = "Pending",
                            TotalPrice = 8640000m
                        },
                        new
                        {
                            BookingId = 103,
                            AdultCount = 1,
                            BookingCode = "BK-20230603-103",
                            BookingDate = new DateTime(2026, 7, 1, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9686),
                            ChildCount = 0,
                            CreatedDate = new DateTime(2026, 7, 2, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9683),
                            CustomerName = "Trần Trung C",
                            DiscountAmount = 0m,
                            Email = "tranc@yahoo.com",
                            FinalPrice = 2500000m,
                            InfantCount = 0,
                            PhoneNumber = "0912333444",
                            ScheduleId = 1,
                            SpecialRequest = "",
                            Status = "Deposited",
                            TotalPrice = 2500000m
                        });
                });

            modelBuilder.Entity("TourManagement.Data.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TourManagement.Data.Models.PromoCode", b =>
                {
                    b.Property<int>("PromoCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoCodeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsage")
                        .HasColumnType("int");

                    b.Property<decimal>("MinBookingValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("PromoCodeId");

                    b.ToTable("PromoCodes");

                    b.HasData(
                        new
                        {
                            PromoCodeId = 1,
                            Code = "TOUR2025",
                            DiscountPercent = 0.10m,
                            EndDate = new DateTime(2027, 7, 2, 9, 19, 46, 53, DateTimeKind.Local).AddTicks(161),
                            IsActive = true,
                            MaxUsage = 100,
                            MinBookingValue = 0m,
                            StartDate = new DateTime(2026, 6, 22, 9, 19, 46, 53, DateTimeKind.Local).AddTicks(160),
                            UsageCount = 0
                        },
                        new
                        {
                            PromoCodeId = 2,
                            Code = "VIP50",
                            DiscountPercent = 0.50m,
                            EndDate = new DateTime(2027, 7, 2, 9, 19, 46, 53, DateTimeKind.Local).AddTicks(167),
                            IsActive = true,
                            MaxUsage = 10,
                            MinBookingValue = 5000000m,
                            StartDate = new DateTime(2026, 6, 22, 9, 19, 46, 53, DateTimeKind.Local).AddTicks(166),
                            UsageCount = 0
                        },
                        new
                        {
                            PromoCodeId = 3,
                            Code = "SUMMER100",
                            DiscountPercent = 0.15m,
                            EndDate = new DateTime(2026, 9, 30, 9, 19, 46, 53, DateTimeKind.Local).AddTicks(171),
                            IsActive = true,
                            MaxUsage = 200,
                            MinBookingValue = 2000000m,
                            StartDate = new DateTime(2026, 6, 22, 9, 19, 46, 53, DateTimeKind.Local).AddTicks(171),
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("TourManagement.Data.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ChildPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExcludedServices")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IncludedServices")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Itinerary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerAdult")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("TourCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TourId");

                    b.HasIndex("IsActive");

                    b.HasIndex("TourCode")
                        .IsUnique();

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            Category = "mien-bac",
                            ChildPrice = 1750000m,
                            CreatedDate = new DateTime(2026, 7, 2, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9543),
                            Days = 3,
                            Description = "Khám phá vẻ đẹp huyền ảo của sương mù Sa Pa và đỉnh Fansipan hùng vĩ.",
                            Destination = "Sa Pa",
                            ExcludedServices = "Chi phí cá nhân, Thuế VAT",
                            Image = "https://images.unsplash.com/photo-1596423735880-5f2a689b903e?q=80&w=600&auto=format&fit=crop",
                            IncludedServices = "Xe đưa đón, Khách sạn 3 sao, Các bữa ăn, Vé tham quan",
                            IsActive = true,
                            Itinerary = "Ngày 1: Hà Nội - Sa Pa | Ngày 2: Bản Cát Cát | Ngày 3: Fansipan - Hà Nội",
                            MaxCapacity = 30,
                            Nights = 2,
                            PricePerAdult = 2500000m,
                            TourCode = "TOUR001",
                            TourName = "Hà Nội - Sa Pa - Cát Cát - Fansipan"
                        },
                        new
                        {
                            TourId = 2,
                            Category = "mien-bac",
                            ChildPrice = 2240000m,
                            CreatedDate = new DateTime(2026, 7, 2, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9571),
                            Days = 2,
                            Description = "Trải nghiệm đẳng cấp 5 sao trên du thuyền khám phá Vịnh Hạ Long và Vịnh Lan Hạ.",
                            Destination = "Hạ Long",
                            ExcludedServices = "Đồ uống trên tàu, Tiền tip",
                            Image = "https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=600&auto=format&fit=crop",
                            IncludedServices = "Phòng du thuyền 5 sao, Các bữa ăn buffet, Chèo thuyền Kayak",
                            IsActive = true,
                            Itinerary = "Ngày 1: Tuần Châu - Vịnh Hạ Long | Ngày 2: Vịnh Lan Hạ - Hà Nội",
                            MaxCapacity = 20,
                            Nights = 1,
                            PricePerAdult = 3200000m,
                            TourCode = "TOUR002",
                            TourName = "Hà Nội - Hạ Long - Vịnh Lan Hạ 2 Ngày 1 Đêm Trên Du Thuyền 5 Sao"
                        },
                        new
                        {
                            TourId = 3,
                            Category = "mien-trung",
                            ChildPrice = 3150000m,
                            CreatedDate = new DateTime(2026, 7, 2, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9577),
                            Days = 4,
                            Description = "Tour miền Trung di sản: Đà Nẵng, Hội An, Bà Nà rực rỡ sắc màu.",
                            Destination = "Đà Nẵng",
                            ExcludedServices = "Chi phí cá nhân",
                            Image = "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?q=80&w=600&auto=format&fit=crop",
                            IncludedServices = "Khách sạn 4 sao, Vé máy bay khứ hồi, Xe đưa đón, Vé tham quan",
                            IsActive = true,
                            Itinerary = "Ngày 1: Đà Nẵng | Ngày 2: Hội An | Ngày 3: Bà Nà Hills | Ngày 4: Sơn Trà - Chợ Hàn",
                            MaxCapacity = 40,
                            Nights = 3,
                            PricePerAdult = 4500000m,
                            TourCode = "TOUR003",
                            TourName = "Đà Nẵng - Hội An - Bà Nà Hills"
                        });
                });

            modelBuilder.Entity("TourManagement.Data.Models.TourSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<decimal>("ActualAdultPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("ActualChildPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuideName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("TourId");

                    b.ToTable("TourSchedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            ActualAdultPrice = 2500000m,
                            ActualChildPrice = 1750000m,
                            AvailableSeats = 20,
                            CreatedDate = new DateTime(2026, 7, 2, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9608),
                            EndDate = new DateTime(2026, 7, 15, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9622),
                            MaxParticipants = 30,
                            StartDate = new DateTime(2026, 7, 12, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9611),
                            Status = "Active",
                            TourId = 1
                        },
                        new
                        {
                            ScheduleId = 2,
                            ActualAdultPrice = 3200000m,
                            ActualChildPrice = 2240000m,
                            AvailableSeats = 15,
                            CreatedDate = new DateTime(2026, 7, 2, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9628),
                            EndDate = new DateTime(2026, 7, 9, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9631),
                            MaxParticipants = 20,
                            StartDate = new DateTime(2026, 7, 7, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9630),
                            Status = "Active",
                            TourId = 2
                        },
                        new
                        {
                            ScheduleId = 3,
                            ActualAdultPrice = 4500000m,
                            ActualChildPrice = 3150000m,
                            AvailableSeats = 25,
                            CreatedDate = new DateTime(2026, 7, 2, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9634),
                            EndDate = new DateTime(2026, 7, 21, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9636),
                            MaxParticipants = 40,
                            StartDate = new DateTime(2026, 7, 17, 9, 19, 46, 52, DateTimeKind.Local).AddTicks(9635),
                            Status = "Active",
                            TourId = 3
                        });
                });

            modelBuilder.Entity("TourManagement.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@tourmanagement.com",
                            FullName = "Administrator",
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "staff@tourmanagement.com",
                            FullName = "Staff Member",
                            PasswordHash = "staff123",
                            Role = "Staff",
                            Username = "staff"
                        },
                        new
                        {
                            UserId = 101,
                            Email = "nguyenvan@gmail.com",
                            FullName = "Nguyễn Văn A",
                            PasswordHash = "nguyenvan123",
                            Role = "Customer",
                            Username = "nguyenvan"
                        },
                        new
                        {
                            UserId = 102,
                            Email = "lethi@gmail.com",
                            FullName = "Lê Thị B",
                            PasswordHash = "lethi123",
                            Role = "Customer",
                            Username = "lethi"
                        });
                });

            modelBuilder.Entity("TourManagement.Data.Models.Booking", b =>
                {
                    b.HasOne("TourManagement.Data.Models.PromoCode", "AppliedPromoCode")
                        .WithMany()
                        .HasForeignKey("PromoCodeId");

                    b.HasOne("TourManagement.Data.Models.TourSchedule", "Schedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourManagement.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("AppliedPromoCode");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourManagement.Data.Models.Payment", b =>
                {
                    b.HasOne("TourManagement.Data.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TourManagement.Data.Models.TourSchedule", b =>
                {
                    b.HasOne("TourManagement.Data.Models.Tour", "Tour")
                        .WithMany("Schedules")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourManagement.Data.Models.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TourManagement.Data.Models.Tour", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TourManagement.Data.Models.TourSchedule", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
