// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourManagement.Data.Context;

#nullable disable

namespace TourManagement.Data.Migrations
{
    [DbContext(typeof(TourManagementDbContext))]
    [Migration("20260624142303_UpdateTourBookingSchema")]
    partial class UpdateTourBookingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TourManagement.Data.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("AdultCount")
                        .HasColumnType("int");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CCCD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ChildCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("InfantCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpecialRequest")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TourManagement.Data.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourId"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ChildPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExcludedServices")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IncludedServices")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Itinerary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerAdult")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("TourCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TourId");

                    b.HasIndex("IsActive");

                    b.HasIndex("TourCode")
                        .IsUnique();

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            AvailableSeats = 20,
                            Category = "mien-bac",
                            ChildPrice = 1750000m,
                            CreatedDate = new DateTime(2026, 6, 24, 21, 23, 3, 32, DateTimeKind.Local).AddTicks(3074),
                            Days = 3,
                            DepartureDate = new DateTime(2026, 7, 4, 21, 23, 3, 32, DateTimeKind.Local).AddTicks(3100),
                            Description = "Khám phá vẻ đẹp huyền ảo của sương mù Sa Pa và đỉnh Fansipan hùng vĩ.",
                            Destination = "Sa Pa",
                            ExcludedServices = "Chi phí cá nhân, Thuế VAT",
                            Image = "https://images.unsplash.com/photo-1596423735880-5f2a689b903e?q=80&w=600&auto=format&fit=crop",
                            IncludedServices = "Xe đưa đón, Khách sạn 3 sao, Các bữa ăn, Vé tham quan",
                            IsActive = true,
                            Itinerary = "Ngày 1: Hà Nội - Sa Pa | Ngày 2: Bản Cát Cát | Ngày 3: Fansipan - Hà Nội",
                            MaxCapacity = 30,
                            Nights = 2,
                            PricePerAdult = 2500000m,
                            TourCode = "TOUR001",
                            TourName = "Hà Nội - Sa Pa - Cát Cát - Fansipan"
                        },
                        new
                        {
                            TourId = 2,
                            AvailableSeats = 15,
                            Category = "mien-bac",
                            ChildPrice = 2240000m,
                            CreatedDate = new DateTime(2026, 6, 24, 21, 23, 3, 32, DateTimeKind.Local).AddTicks(3118),
                            Days = 2,
                            DepartureDate = new DateTime(2026, 6, 29, 21, 23, 3, 32, DateTimeKind.Local).AddTicks(3123),
                            Description = "Trải nghiệm đẳng cấp 5 sao trên du thuyền khám phá Vịnh Hạ Long và Vịnh Lan Hạ.",
                            Destination = "Hạ Long",
                            ExcludedServices = "Đồ uống trên tàu, Tiền tip",
                            Image = "https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=600&auto=format&fit=crop",
                            IncludedServices = "Phòng du thuyền 5 sao, Các bữa ăn buffet, Chèo thuyền Kayak",
                            IsActive = true,
                            Itinerary = "Ngày 1: Tuần Châu - Vịnh Hạ Long | Ngày 2: Vịnh Lan Hạ - Hà Nội",
                            MaxCapacity = 20,
                            Nights = 1,
                            PricePerAdult = 3200000m,
                            TourCode = "TOUR002",
                            TourName = "Hà Nội - Hạ Long - Vịnh Lan Hạ 2 Ngày 1 Đêm Trên Du Thuyền 5 Sao"
                        },
                        new
                        {
                            TourId = 3,
                            AvailableSeats = 25,
                            Category = "mien-trung",
                            ChildPrice = 3150000m,
                            CreatedDate = new DateTime(2026, 6, 24, 21, 23, 3, 32, DateTimeKind.Local).AddTicks(3126),
                            Days = 4,
                            DepartureDate = new DateTime(2026, 7, 9, 21, 23, 3, 32, DateTimeKind.Local).AddTicks(3129),
                            Description = "Tour miền Trung di sản: Đà Nẵng, Hội An, Bà Nà rực rỡ sắc màu.",
                            Destination = "Đà Nẵng",
                            ExcludedServices = "Chi phí cá nhân",
                            Image = "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?q=80&w=600&auto=format&fit=crop",
                            IncludedServices = "Khách sạn 4 sao, Vé máy bay khứ hồi, Xe đưa đón, Vé tham quan",
                            IsActive = true,
                            Itinerary = "Ngày 1: Đà Nẵng | Ngày 2: Hội An | Ngày 3: Bà Nà Hills | Ngày 4: Sơn Trà - Chợ Hàn",
                            MaxCapacity = 40,
                            Nights = 3,
                            PricePerAdult = 4500000m,
                            TourCode = "TOUR003",
                            TourName = "Đà Nẵng - Hội An - Bà Nà Hills"
                        });
                });

            modelBuilder.Entity("TourManagement.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@tourmanagement.com",
                            FullName = "Administrator",
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "staff@tourmanagement.com",
                            FullName = "Staff Member",
                            PasswordHash = "staff123",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("TourManagement.Data.Models.Booking", b =>
                {
                    b.HasOne("TourManagement.Data.Models.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourManagement.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourManagement.Data.Models.Tour", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
